name: Compilar APK de YT

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Redirigir código
      uses: actions/checkout@v4

    - name: Configurar Cache de Buildozer
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer
        # Cambiamos la clave a 'v2' para forzar a GitHub a borrar la caché vieja y corrupta
        key: ${{ runner.os }}-buildozer-v2-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildozer-v2-

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev libglib2.0-dev libffi-dev libssl-dev
        sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5-dev libgdbm-dev libncursesw5-dev libreadline-dev uuid-dev libgdbm-compat-dev
        sudo apt-get install -y openjdk-17-jdk-headless unzip zip
        pip3 install --user --upgrade buildozer cython virtualenv

    - name: Compilar APK con Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        # Quitamos cualquier intento de parche manual obsoleto
        buildozer android debug
        
    - name: Subir APK terminada
      uses: actions/upload-artifact@v4
      with:
        name: YT-APK-Debug
        path: bin/*.apk
