name: Compilar APK de YT

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Redirigir código
      uses: actions/checkout@v4

    - name: Configurar Cache de Buildozer (Forzar Limpieza)
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          .buildozer
        # Cambiamos a v3_limpio para ignorar por completo la caché corrupta anterior
        key: ${{ runner.os }}-buildozer-v3_limpio-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildozer-v3_limpio-

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev libglib2.0-dev libffi-dev libssl-dev
        sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5-dev libgdbm-dev libncursesw5-dev libreadline-dev uuid-dev libgdbm-compat-dev
        # Forzamos openjdk-17 completo para evitar que use Java 11 por error
        sudo apt-get install -y openjdk-17-jdk unzip zip
        pip3 install --user --upgrade buildozer cython virtualenv wheel setuptools

    - name: Compilar APK con Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        
        # 1. Crear de forma preventiva el directorio de licencias
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        
        # 2. Inyectar hashes de aceptación para evitar la traba de Google Build-Tools 37
        echo -e "\n89346db307477b1b6f88c27a47423e291c81e53d\n24333f1a50b1b1c67414e811d782547ef223d721\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo -e "\n84934015526d973048dd7765245a4475317748ca" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
        
        # 3. Lanzar la compilación interactiva forzada
        yes | buildozer android debug
        
    - name: Subir APK terminada
      uses: actions/upload-artifact@v4
      with:
        name: YT-APK-Debug
        path: bin/*.apk
        
